
services:
  api:
    image: khushbu308/loan-api:v3
    container_name: loan_api
    ports:
      - "8000:8000"

  ui:
    image: khushbu308/loan-ui:v3
    container_name: loan_ui
    ports:
      - "8501:8501"
    depends_on:
      - api
